name: Check for build warnings
on: [pull_request_target]
jobs:
  status_checker_job:
    runs-on: ubuntu-latest
    name: Checks the OpenPublishing.Build status check for build warnings
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@main
      with:
        egress-policy: audit
    - uses: MicrosoftDocs/quantum-docs-private/.github/actions/status-checker@main
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
